### ISSUE TITLE
Deployables do not reset on renting for second term.

### ISSUE THREAD

**Issue by minutechoochoo** [shady14u/Hotel#1]
Specifically tested with sleeping bags.

Steps to reproduce

Place down door frame and door, with codelock. run /hotel_new and /hotel commands. Set duration of rent to 30 seconds and rent price to one scrap for testing purposes. Place down a bedroom and do /hotel rooms to refresh rooms and have plugin learn the room and deployables visibile to door. Do hotel_save, which saves the hotel and sets the hotel to be rented. Transfer sleepingbag over to random individual. Rent room, when renting the room, the deployable sleepingbag will be transfered back to you. Wait till rent expires, sleeping bag does not reset. Transfer sleeping bag over to random individual again, re rent the room for the second term, bed does not transfer ownership like the first term.

**Comment by shady14u** [comment]
When rooms are made and the /rooms command is run it records ALL items the lock can see.. and ONLY that lock can see. When a NEW renter rents the room anything not default is removed and the room resets.. If the SAME renter rents again nothing changes. It must be a different renter to reset the room. This is to allow the same renter to rent many days.  If they forgot to extend and some one else rents it, the room resets and their loot is lost
