### ISSUE TITLE
Request: Hotel Room Resets on rent expiration.

### ISSUE THREAD

**Issue by minutechoochoo** [shady14u/Hotel#2]
As is deployables are suppose to reset, but as the time of this post being published that is broken. I am suggesting a request to extend that feature to structures and all buildables. This would allow individuals to build and place deployables and on the expiration their rooms would reset and the hotel would delete everything they placed or built.

**Comment by shady14u** [comment]
Rooms Reset on a NEW Unique Renter, Once a different renter buys the room
